### ISSUE TITLE
Error Deploying the Backend

### ISSUE THREAD

**Issue by skgupta507** [immdipu/Beatstreet-backend#1]
Hi
I am Unable to Deploy the Backend to Adaptable.io When i Deploy the code i get the Error "Container failed to deploy: The container failed to start and listen on the port defined by the PORT environment variable." Can U help me troubleshoot the Issue or shuld i deploy it on some other Website like Render.com or Herouka.app.
i will be waiting for your response.
And thanks for sharing the Backend repo with  us.

**Comment by immmdipu** [comment]
Did you try to run it locally first. if its running in your local computer then i guess the issue is related to how you deploying on Adaptable.io. You can try to deploy on other platform like cyclic.sh for free.

**Comment by immdipu** [comment]
Did you try to run it locally first?. if its running in your local computer then i guess the issue is related to how you deploying on Adaptable.io. You can try to deploy on other platform like cyclic.sh for free.

**Comment by skgupta507** [comment]
Hey @immdipu i tried on my local machine as u said but its not working locally also i have tried changing the default port from 3000 to 27017 which is default port for mangodb database but i still get the same error. i have attached sime screenshot of it u can look at them guide me how to fix this. 

[CYCLIC] ERROR: No response from server on port 3000
 MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (/var/task/node_modules/mongodb-connection-string-url/lib/index.js:86:19)
    at parseOptions (/var/task/node_modules/mongodb/lib/connection_string.js:204:17)
    at new MongoClient (/var/task/node_modules/mongodb/lib/mongo_client.js:46:63)
    at _createMongoClient (/var/task/node_modules/mongoose/lib/connection.js:851:14)
    at NativeConnection.openUri (/var/task/node_modules/mongoose/lib/connection.js:705:29)
    at Mongoose.connect (/var/task/node_modules/mongoose/lib/index.js:406:15)
    at Object.<anonymous> (/var/task/server.js:9:4)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
 [CYCLIC] ERROR: No response from server on port 3000
 [CYCLIC] ERROR: No response from server on port 3000

![image](https://github.com/immdipu/Beatstreet-backend/assets/131786207/b51a46ce-de01-473e-be4d-a41823a22042)
![image](https://github.com/immdipu/Beatstreet-backend/assets/131786207/89e26534-d320-484f-bd97-287986fd6a06)
![image](https://github.com/immdipu/Beatstreet-backend/assets/131786207/1ab7b529-6080-430c-b9ff-53cbf4911c78)
![image](https://github.com/immdipu/Beatstreet-backend/assets/131786207/f49550c1-6c68-4c09-afb0-eae006144efe)

kindly help and guide me with this issue.
